### ISSUE TITLE
selinux httpd_can_network_connect does not work in ansible

### ISSUE THREAD

**Issue by christianhilbrands** [molgenis/molgenis-ops-galaxy#51]
probbably something to do with cleaning the vm true the openstack rebuilt command in the openstack ui. need to check with another command.

workaround:
- do it by hand, execute command: setsebool -P httpd_can_network_connect on
-

**Comment by DickPostma** [comment]
The selinux (posix) ansible library uses python3 functions. Probably the cleanup messed up the default python environment. 
You can setup python with linux alternatives command or use ansible with an workaround:

`ansible-playbook playbook.yml -e 'ansible_python_interpreter=/usr/bin/python3'
